/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package offlinetestingplatform;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Dictionary;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Vector;

public class quizInterface extends javax.swing.JFrame {

    private Vector<question> questions;

    public void displaySelectedQuestion(int selectedQuestionIndex){

        buttonGroup1.clearSelection();

        question requiredQuestion = questions.get(selectedQuestionIndex-1);

        questionDisplay.setText(requiredQuestion.getContent());

        Dictionary optionList = requiredQuestion.getOptions();

        ArrayList<String> options = new ArrayList<>();

        for(Enumeration i = optionList.elements(); i.hasMoreElements();){
            options.add((String) i.nextElement());


        }

        Collections.reverse(options);

        option1.setText(options.get(0));
        option2.setText(options.get(1));
        option3.setText(options.get(2));
        option4.setText(options.get(3));

        submit.setEnabled(!requiredQuestion.isAttempted());

    }

    public void fillQuestionsFromCSV(){

        //UPDATE FILE PATH TO RUN PROJECT
        String questionFilePath = "C:\\Users\\DELL\\Desktop\\work\\OOM\\miniproject\\OfflineQuizSoftware\\src\\data\\questionStore.csv";

        File questionFile = new File(questionFilePath);

        try {


            BufferedReader questionReader = new BufferedReader(new FileReader(questionFile));

            Object[] questionImportList = questionReader.lines().toArray();

            questionReader.close();

            for(Object question: questionImportList){

                String questionString = question.toString().trim();
                String[] questionArray = questionString.split(",");

                ArrayList<String> options = new ArrayList<>();

                options.add(questionArray[1]);
                options.add(questionArray[2]);
                options.add(questionArray[3]);
                options.add(questionArray[4]);

                questions.add(new question(questionArray[0], options, Integer.parseInt(questionArray[5].trim())));

            }




        } catch (FileNotFoundException ex) {

            Logger.getLogger(quizInterface.class.getName()).log(Level.SEVERE, null, ex);

        } catch (IOException ex) {
            Logger.getLogger(quizInterface.class.getName()).log(Level.SEVERE, null, ex);
        }



    }

    public void fillComboBox(){

        String[] modelInput = new String[questions.size()];

        for(int i=0; i< questions.size(); i++){
            modelInput[i] = Integer.toString(i+1);
        }

        questionPicker.setModel(new javax.swing.DefaultComboBoxModel<>(modelInput));

    }

    /**
     * Creates new form quizInterface
     */
    public quizInterface(Vector<question> questionsSentIn) {
        initComponents();
//        questions = new Vector<>();
//        fillQuestionsFromCSV();

        questions = questionsSentIn;

        fillComboBox();
        displaySelectedQuestion(1);


        questionPicker.addItemListener(new ItemListener(){

            @Override
            public void itemStateChanged(ItemEvent e) {
                
                if(e.getStateChange() == ItemEvent.SELECTED){
                    
                    String item = e.getItem().toString();
                    Integer optionSelected = Integer.parseInt(item);
                    
                    displaySelectedQuestion(optionSelected);
                }
            }

            
        });

        java.awt.EventQueue.invokeLater(() -> this.setVisible(true));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        questionPicker = new javax.swing.JComboBox();
        questionDisplay = new javax.swing.JLabel();
        option1 = new javax.swing.JRadioButton();
        option2 = new javax.swing.JRadioButton();
        option3 = new javax.swing.JRadioButton();
        option4 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        submit = new javax.swing.JButton();
        remark = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("FreeSans", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Question");

        questionPicker.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questionPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questionPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        questionDisplay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        questionDisplay.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        questionDisplay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        option1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(option1);
        option1.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N

        option2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(option2);
        option2.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N

        option3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(option3);
        option3.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N

        option4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(option4);
        option4.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        submit.setBackground(new java.awt.Color(153, 255, 153));
        submit.setForeground(new java.awt.Color(0, 0, 0));
        submit.setText("Submit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(submit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(remark, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(option4)
                    .addComponent(option3)
                    .addComponent(option2)
                    .addComponent(option1)
                    .addComponent(questionDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(questionDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(option1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(option2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(option3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(option4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(remark, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton option1;
    private javax.swing.JRadioButton option2;
    private javax.swing.JRadioButton option3;
    private javax.swing.JRadioButton option4;
    private javax.swing.JLabel questionDisplay;
    private javax.swing.JComboBox questionPicker;
    private javax.swing.JLabel remark;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
